name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
      
    - name: Build
      run: dotnet build --configuration Release -p:Version=${{ github.ref_name }}
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: dotnet publish
      run: dotnet publish --no-build --configuration Release -p:Version=${{ github.ref_name }} -p:SciuridaeApiKey=${{ secrets.SCIURIDAEAPIKEY }}
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: Installer
        path: ./SciuridaeReleases
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: false
        generate_release_notes: true
        files: |
          ./SciuridaeReleases/RELEASES
          ./SciuridaeReleases/ColorKraken-${{ github.ref_name }}-full.nupkg
          ./SciuridaeReleases/ColorKraken-${{ github.ref_name }}-delta.nupkg
          ./SciuridaeReleases/ColorKrakenSetup.exe

    #- name: Upload to blob
    #  run: az storage copy -s "./SciuridaeReleases/ColorKrakenSetup.exe" -d "https://sciuridae.blob.core.windows.net/test/ColorKrakenSetup.exe" --connection-string "${{ secrets.BLOB_CONNECTION_STRING }}"
    