name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
      
    - name: Build
      run: dotnet build --configuration Release -p:Version=${{ github.ref_name }}
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: dotnet publish
      run: dotnet publish --no-build --configuration Release -p:Version=${{ github.ref_name }} -p:SciuridaeApiKey=${{ secrets.SCIURIDAEAPIKEY }}
    
    - name: Run Scan
      run: Start-MpScan -ScanType QuickScan -ScanPath ./SciuridaeReleases

    - name: Show Scan Results
      run: Get-MpThreatDetection

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: Installer
        path: ./SciuridaeReleases
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          ./SciuridaeReleases/RELEASES
          ./SciuridaeReleases/ColorKraken-${{ github.ref_name }}-full.nupkg
          ./SciuridaeReleases/ColorKraken-${{ github.ref_name }}-delta.nupkg
          ./SciuridaeReleases/ColorKrakenSetup.exe

    - name: Upload to blob
      uses: bacongobbler/azure-blob-storage-upload@main
      with:
        source_dir: SciuridaeReleases
        container_name: test
        connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
        extra_args: '--pattern ColorKraken*'
        overwrite: 'true'
          
    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v3
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          ./SciuridaeReleases/ColorKrakenSetup.exe